codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        enabled: yes
        target: 1
        threshold: 0.5%
    patch:
      default:
        enabled: yes
        target: auto
        threshold: 0%
ignore:
  - doc
  - .github
  - .git
  - test-root
  - mac
